# Please translate lists into ---. Please keep city names and land-names in english like Anafola, Benfriege, Demetry, Enfeir, Fodker, Kubani, Glaser, Kubani, Pafiz, Scetcher, Starfex, Tamarania, Tamariza, Tutalu, Zinzibar, and Valdhomir. And keep the key english words in that are best understood in english for this language.
quotes = {
    'monk': ['True strength lies in the mastery of one’s mind. Let your thoughts be like water—flowing and adaptable to the shape of every circumstance.',
             'In the garden of your life, cultivate compassion and wisdom as diligently as you would any precious flower. For these virtues will bloom into peace and understanding.',
             "Beware of the wilderness, young one."],
    'enfeir_warrior': ['This war with Zinizbar started long ago when they stole something very important to us...',
                       'After realizing the damage our actions caused, Enfeir decided to rebuild and be an example that change is possible.',
                       'Enfeir and Zinzibar once held the strongest alliance in the land, before we were betrayed.'],
    'zinzibar_warrior': ['Enfeir says we betrayed them. Ha! Our emissaries were sent to discuss politics and Enfeir murdered them!',
                         'They say you must be adept at sneak to find our hidden lair, but the truth is we decide who we allow to join our ranks.',
                         'They call us the dark city. What have we done to deserve a name so foul?',
                         "The master of the hiddlen lair recently came back from the wilderness. Ever since his return, he has been saying crazy things about a wizard experimenting on monsters..."],
    'benfriege_warrior': ['Over the years the wilderness has been expanding. We fear as this expansion continues, our city will be engulfed and we will lose everything.',
                          'People come here to isolate themselves from the rest of the world and focus on their intellectual pursuits.',
                          #'Being so isolated from the rest of the world, our city decided knowledge was essential to our survival.',
                          'It is said that there is a very ancient, very powerful man wandering the wilderness...',
                          'We have recovered some books from the wilderness. It appears to be records from some ancient city. The last date mentioned a wizard visiting them from Anafola...'],
    'anafola_warrior': ["If your goal is to fight over and over, summoning isn't for you.",
                        "Your summons will fight for you but make no mistake, they do not enjoy it.",
                        "When excavating or gathering, your summons can help look with you!",
                        "It's rumored that our summons are from the same place as all these monsters came from. The veil between the dimensions is growing thinner and thinner.",
                        "Some of the more talented summoners can communicate with their creatures. The district leaders have told us it seems the stronger creatures are grouping in the wilderness. Who knows what they're planning...",
                        "It is said that the man who founded our city had a brother who was the strongest summoner in history. The story goes he one day went to the wilderness and never returned."],
    'demetry_warrior': ["If you are skilled enough, jobs here pay more than anywhere else in Valdhomir.",
                        "Demetry, no better place to earn your riches in all of Valdhomir!",
                        "The more recognized you are, the more the bank is willing to loan you.",
                        "Our city gained its riches thanks to our central location. Demetry is the trading hub of Valdhomir.",
                        "Many of our people become traders who sell items at great prices to travelers."],
    'fodker_warrior': ['We used to be a prosperous city, our villages booming with production. I still remember the screams when those bandits burned them down.',
                       'It is rumored that someone in our villages discovered something ancient and powerful. No one quite knows the whole story as the bandits burned their ledgers and all that knowledge was lost.',
                       'I cant wait to find another one of those bandits. I will avenge my people!'],
    'glaser_warrior': ['Why do these cities always have to fight? Basing their value on the amount of blood they shed. I wish we could all just live peacefully and together.',
                       'Theres been rumors going around that our chiefs are staging a conference. One with leaders from all cities to discuss working together to stop the wilderness from growing.',
                       'Many people have forgotten the power we possess. There is a reason why other cities acknowledge our efforts.',
                       "It doesn't seem to matter how many bandits we defeat. It's as if they are coming from the void."],
    'kubani_warrior': ['Kubani was one of the first cities ever founded, we hold knowledge many others have forgotten.',
                       'Many people view their ancestors as if they wouldnt understand circumstances today, when in fact they understood more than we can possibly imagine.',
                       'The ancient ways hold abilities that some people might see as unfair.',
                       'Based on our records, the wilderness has been expanding slowly over time. It is said there was once a city there, but it has been totally engulfed and lost forever.'],
    'pafiz_warrior': ['Everyone here is orginially descended from Tamariza. We decided their ways were too old-fashioned, we are more open minded than them.',
                      'If you have the time, visit the meditation chamber before your next adventure. This will ensure you return safely.',
                      'When you understand what fighting style is weak to what, it will be clear which battles to fight.'],
    'scetcher_warrior': ['Our value is determined by the strength we possess!',
                         'Let us fight, for the glory of Scetcher!',
                         'I am itching for another fight',
                         'The Arena. A place full of blood and glory! Maybe I should sign up for another tournament.',
                         'If you really wish to challenge yourself, the strongest monsters live in the wilderness.'],
    'starfex_warrior': ['If your wondering about the empty display cases at the top level of the museum, my father told me that is where the legendary swords were once placed',
                        'Rumor has it if you collect 6 of the same fragments and bring them to the museum, an ancient power will be released.',
                        'My father always wanted me to become a caretaker of the museum, but I wish to set my own path.',
                        'Our ancestors once held strange weapons. We found them inefficient and hard to use so we improved upon them.'],
    'tamarania_warrior': ['We pride ourselves on being the best smithers in Valdhomir! If you find any rare ores bring them here!',
                          'Oh? What is my weapon made of? I smithed this myself with aluminum ore!',
                          'The rarest of ores can be found in the battlefield between Zinzibar and Enfeir. However if you think you are strong enough, you can excavate in the wilderness to find them.'],
    'tamariza_warrior': ["Many people don't understand the difference between wizard and elemental users. We can do things they can't like create a forcefield to block trooper shots.",
                         "Depending on which wizard tower membership you have, your rewards will differ. With platinum you could teleport all the way to Zinzibar instantly!",
                         "These cities love to say they could compete with us. In reality, Tamarania is the only threat and we will deal with them in time.",
                         "The wilderness has expanded greatly over the years. Most people who venture in never return."],
    'tutalu_warrior': ['This land used to be full of caves before our leaders slayed all the monsters dwelling here and created this city.',
                       'The Hunters Guild. We pride ourselves on making Valdhomir safer from the looming monster threat.',
                       'People think monsters are mindless beasts. However, some of them possess great knowledge and ability. We must stop them from assembling at any cost!',
                       'The most dangerous of all monsters dwell in the wildnerness. Citizens of Benfriege and Anafola might know more...'],
    'lost_friend': ["Thank God you found me! You can't imagine the atrocities i've witnessed",
                    "I don't remember much about when I was taken, but I was trapped in the wilderness for what seemed like forever. The monsters there.... they did not act like normal monsters. It's as if they were working towards a goal.",
                    "I saw something I can't quite explain... There was this old man in the wilderness and the monsters seemed to listen to him. It's as if he was controling them.",
                    "When the old man found me, he tried to turn me on his side. Said he needed a strong #2 like me for his plans. When I refused, he sicked his monsters onto me.",
                    "I barely escaped with my life, after that I've been hiding ever since."],
    'lost_pet_orange': ["Meow!"],
    'lost_pet_black': ["Meow."],
    'lost_pet_green': ["Meow!"],
    'lost_pet_white': ["Meow!"],
}